# Generated by Django 6.0.7 on 2026-08-02 12:10

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0004_master_chart"),
        ("customers", "0002_customer_customer_name_normalized_unique_and_more"),
        ("payments", "0002_alter_payment_journal_entry"),
        ("purchases", "0009_alter_purchaseline_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="payment_amount_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("customer__isnull", False),
                        ("kind", "receive"),
                        ("supplier__isnull", True),
                    ),
                    models.Q(
                        ("customer__isnull", True),
                        ("kind", "pay"),
                        ("supplier__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="payment_party_matches_kind",
            ),
        ),
    ]
