# Generated by Django 6.0.7 on 2026-07-15 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_remove_jewelryitem_making_charge_per_gram"),
        ("purchases", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchaseline",
            name="item",
        ),
        migrations.AddField(
            model_name="purchaseline",
            name="category",
            field=models.CharField(
                choices=[
                    ("ring", "Ring"),
                    ("necklace", "Necklace"),
                    ("bracelet", "Bracelet"),
                    ("earring", "Earring"),
                    ("chain", "Chain"),
                    ("pendant", "Pendant"),
                    ("other", "Other"),
                ],
                default="ring",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="purchaseline",
            name="created_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_lines",
                to="inventory.jewelryitem",
            ),
        ),
        migrations.AddField(
            model_name="purchaseline",
            name="karat",
            field=models.IntegerField(
                choices=[(18, "18K"), (21, "21K"), (24, "24K")], default=21
            ),
        ),
        migrations.AddField(
            model_name="purchaseline",
            name="name",
            field=models.CharField(default="", max_length=120),
        ),
        migrations.AddField(
            model_name="purchaseline",
            name="stone_details",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="purchaseline",
            name="weight_grams",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name="purchaseline",
            name="unit_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
