# Generated by Django 6.0.7 on 2026-07-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0003_purchase_journal_entry"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseline",
            name="barcode",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Scan or type; leave blank to auto-generate",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="purchaseline",
            name="location",
            field=models.CharField(
                choices=[("safe", "Safe"), ("showcase", "Showcase")],
                default="safe",
                max_length=20,
            ),
        ),
    ]
