# Generated by Django 6.0.7 on 2026-08-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0004_purchaseline_barcode_purchaseline_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="is_opening",
            field=models.BooleanField(
                default=False,
                help_text="Stock you already owned, brought onto the books (e.g. a CSV import)",
            ),
        ),
    ]
