# Generated by Django 6.0.7 on 2026-08-02 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_jewelryitem_source_purchase_line"),
        ("purchases", "0006_alter_purchase_journal_entry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseline",
            name="created_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="purchase_lines",
                to="inventory.jewelryitem",
            ),
        ),
    ]
