# Generated by Django 6.0.7 on 2026-08-02 11:24

import django.db.models.functions.text
from django.db import migrations, models


def normalize_name(value):
    return " ".join((value or "").split())


def normalize_phone(value):
    for character in (" ", "-", "(", ")"):
        value = (value or "").replace(character, "")
    return value


def prepare_suppliers(apps, schema_editor):
    Supplier = apps.get_model("purchases", "Supplier")
    Purchase = apps.get_model("purchases", "Purchase")
    Payment = apps.get_model("payments", "Payment")
    survivors = {}

    for supplier in Supplier.objects.order_by("created_at", "id"):
        supplier.name = normalize_name(supplier.name)
        supplier.phone = normalize_phone(supplier.phone)
        supplier.email = (supplier.email or "").strip().lower()
        key = supplier.name.lower()
        survivor = survivors.get(key)

        if survivor is None:
            supplier.save(update_fields=["name", "phone", "email"])
            survivors[key] = supplier
            continue

        if survivor.phone and supplier.phone and survivor.phone != supplier.phone:
            raise RuntimeError(
                f"Suppliers {survivor.pk} and {supplier.pk} have the same name "
                "but conflicting phone numbers; merge them manually before migrating."
            )
        if survivor.email and supplier.email and survivor.email != supplier.email:
            raise RuntimeError(
                f"Suppliers {survivor.pk} and {supplier.pk} have the same name "
                "but conflicting email addresses; merge them manually before migrating."
            )

        Purchase.objects.filter(supplier_id=supplier.pk).update(supplier_id=survivor.pk)
        Payment.objects.filter(supplier_id=supplier.pk).update(supplier_id=survivor.pk)
        for field in ("phone", "email", "notes"):
            if not getattr(survivor, field) and getattr(supplier, field):
                setattr(survivor, field, getattr(supplier, field))
        survivor.save(update_fields=["phone", "email", "notes"])
        supplier.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_alter_payment_journal_entry"),
        ("purchases", "0007_alter_purchaseline_created_item"),
    ]

    operations = [
        migrations.RunPython(prepare_suppliers, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="supplier",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower(
                    django.db.models.functions.text.Trim("name")
                ),
                name="supplier_name_normalized_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="supplier",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Trim("phone"),
                condition=models.Q(("phone", ""), _negated=True),
                name="supplier_phone_normalized_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="supplier",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower(
                    django.db.models.functions.text.Trim("email")
                ),
                condition=models.Q(("email", ""), _negated=True),
                name="supplier_email_normalized_unique",
            ),
        ),
    ]
