# Generated by Django 6.0.7 on 2026-08-02 11:38

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_jewelryitem_source_purchase_line"),
        ("purchases", "0008_supplier_supplier_name_normalized_unique_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseline",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="purchaseline",
            name="unit_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="purchaseline",
            name="weight_grams",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(Decimal("0.001"))],
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseline",
            constraint=models.CheckConstraint(
                condition=models.Q(("weight_grams__gt", 0)),
                name="purchase_line_weight_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseline",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_cost__gt", 0)),
                name="purchase_line_unit_cost_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="purchase_line_quantity_positive",
            ),
        ),
    ]
