# Generated by Django 6.0.7 on 2026-07-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JewelryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ring", "Ring"),
                            ("necklace", "Necklace"),
                            ("bracelet", "Bracelet"),
                            ("earring", "Earring"),
                            ("chain", "Chain"),
                            ("pendant", "Pendant"),
                            ("other", "Other"),
                        ],
                        default="ring",
                        max_length=20,
                    ),
                ),
                (
                    "karat",
                    models.IntegerField(
                        choices=[(18, "18K"), (21, "21K"), (24, "24K")], default=21
                    ),
                ),
                ("weight_grams", models.DecimalField(decimal_places=3, max_digits=8)),
                ("stone_details", models.CharField(blank=True, max_length=200)),
                ("cost_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("selling_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
