# Generated by Django 6.0.7 on 2026-07-13 05:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoldRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "karat",
                    models.IntegerField(
                        choices=[(18, "18K"), (21, "21K"), (24, "24K")]
                    ),
                ),
                (
                    "price_per_gram",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.AddField(
            model_name="jewelryitem",
            name="making_charge_per_gram",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
