# Generated by Django 6.0.7 on 2026-07-14 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_goldrate_jewelryitem_making_charge_per_gram"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jewelryitem",
            name="selling_price",
        ),
    ]
