# Generated by Django 6.0.7 on 2026-07-14 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_remove_jewelryitem_selling_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jewelryitem",
            name="making_charge_per_gram",
        ),
    ]
