# Generated by Django 6.0.7 on 2026-07-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_remove_jewelryitem_making_charge_per_gram"),
    ]

    operations = [
        migrations.AddField(
            model_name="jewelryitem",
            name="barcode",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="jewelryitem",
            name="location",
            field=models.CharField(
                choices=[("safe", "Safe"), ("showcase", "Showcase")],
                default="safe",
                max_length=20,
            ),
        ),
    ]
