# Generated by Django 6.0.7 on 2026-08-02 11:10

import django.db.models.deletion
from django.db import migrations, models


def connect_existing_purchase_items(apps, schema_editor):
    JewelryItem = apps.get_model("inventory", "JewelryItem")
    PurchaseLine = apps.get_model("purchases", "PurchaseLine")

    for line in PurchaseLine.objects.exclude(created_item_id=None).iterator():
        JewelryItem.objects.filter(
            pk=line.created_item_id,
            source_purchase_line_id=None,
        ).update(source_purchase_line_id=line.pk)


def disconnect_existing_purchase_items(apps, schema_editor):
    JewelryItem = apps.get_model("inventory", "JewelryItem")
    JewelryItem.objects.update(source_purchase_line_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_jewelryitem_barcode_jewelryitem_location"),
        ("purchases", "0005_purchase_is_opening"),
    ]

    operations = [
        migrations.AddField(
            model_name="jewelryitem",
            name="source_purchase_line",
            field=models.OneToOneField(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_stock_item",
                to="purchases.purchaseline",
            ),
        ),
        migrations.RunPython(
            connect_existing_purchase_items,
            disconnect_existing_purchase_items,
        ),
    ]
