# Generated by Django 6.0.7 on 2026-08-02 11:24

import django.db.models.functions.text
from django.db import migrations, models


def normalize_name(value):
    return " ".join((value or "").split())


def normalize_phone(value):
    for character in (" ", "-", "(", ")"):
        value = (value or "").replace(character, "")
    return value


def prepare_customers(apps, schema_editor):
    Customer = apps.get_model("customers", "Customer")
    Sale = apps.get_model("sales", "Sale")
    Payment = apps.get_model("payments", "Payment")
    survivors = {}

    for customer in Customer.objects.order_by("created_at", "id"):
        customer.name = normalize_name(customer.name)
        customer.phone = normalize_phone(customer.phone)
        customer.email = (customer.email or "").strip().lower()
        key = customer.name.lower()
        survivor = survivors.get(key)

        if survivor is None:
            customer.save(update_fields=["name", "phone", "email"])
            survivors[key] = customer
            continue

        if survivor.phone and customer.phone and survivor.phone != customer.phone:
            raise RuntimeError(
                f"Customers {survivor.pk} and {customer.pk} have the same name "
                "but conflicting phone numbers; merge them manually before migrating."
            )
        if survivor.email and customer.email and survivor.email != customer.email:
            raise RuntimeError(
                f"Customers {survivor.pk} and {customer.pk} have the same name "
                "but conflicting email addresses; merge them manually before migrating."
            )

        Sale.objects.filter(customer_id=customer.pk).update(customer_id=survivor.pk)
        Payment.objects.filter(customer_id=customer.pk).update(customer_id=survivor.pk)
        for field in ("phone", "email", "address", "notes"):
            if not getattr(survivor, field) and getattr(customer, field):
                setattr(survivor, field, getattr(customer, field))
        survivor.save(update_fields=["phone", "email", "address", "notes"])
        customer.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
        ("payments", "0002_alter_payment_journal_entry"),
        ("sales", "0005_alter_sale_journal_entry_alter_saleline_item"),
    ]

    operations = [
        migrations.RunPython(prepare_customers, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower(
                    django.db.models.functions.text.Trim("name")
                ),
                name="customer_name_normalized_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Trim("phone"),
                condition=models.Q(("phone", ""), _negated=True),
                name="customer_phone_normalized_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower(
                    django.db.models.functions.text.Trim("email")
                ),
                condition=models.Q(("email", ""), _negated=True),
                name="customer_email_normalized_unique",
            ),
        ),
    ]
