# Generated by Django 6.0.7 on 2026-08-01 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0002_opening_balance_accounts"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="is_group",
            field=models.BooleanField(
                default=False,
                help_text="A heading that totals its children. You cannot post transactions to a group account.",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="The heading this account sits under, e.g. 1011 Cash on Hand sits under 1010",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to="accounting.account",
            ),
        ),
    ]
