# Generated by Django 6.0.7 on 2026-08-02 12:32

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0004_master_chart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journalline",
            name="credit",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="journalline",
            name="debit",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddConstraint(
            model_name="journalline",
            constraint=models.CheckConstraint(
                condition=models.Q(("debit__gte", 0)),
                name="journal_line_debit_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="journalline",
            constraint=models.CheckConstraint(
                condition=models.Q(("credit__gte", 0)),
                name="journal_line_credit_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="journalline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("credit", 0), ("debit__gt", 0)),
                    models.Q(("credit__gt", 0), ("debit", 0)),
                    _connector="OR",
                ),
                name="journal_line_exactly_one_side",
            ),
        ),
    ]
