# Generated by Django 6.0.7 on 2026-07-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_remove_sale_customer_name_sale_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="saleline",
            name="making_charge_per_gram",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
