# Generated by Django 6.0.7 on 2026-07-16 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0001_initial"),
        ("sales", "0003_saleline_making_charge_per_gram"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="journal_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="accounting.journalentry",
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="on_credit",
            field=models.BooleanField(
                default=False, help_text="Sold on credit (customer owes you)"
            ),
        ),
    ]
