# Generated by Django 6.0.7 on 2026-08-02 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0004_master_chart"),
        ("inventory", "0006_jewelryitem_source_purchase_line"),
        ("sales", "0004_sale_journal_entry_sale_on_credit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="journal_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="accounting.journalentry",
            ),
        ),
        migrations.AlterField(
            model_name="saleline",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="inventory.jewelryitem"
            ),
        ),
    ]
