# Generated by Django 6.0.7 on 2026-08-02 11:53

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0004_master_chart"),
        ("customers", "0002_customer_customer_name_normalized_unique_and_more"),
        ("inventory", "0006_jewelryitem_source_purchase_line"),
        ("sales", "0005_alter_sale_journal_entry_alter_saleline_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="discount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="saleline",
            name="gold_price_per_gram",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="saleline",
            name="making_charge_per_gram",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="saleline",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AddConstraint(
            model_name="sale",
            constraint=models.CheckConstraint(
                condition=models.Q(("discount__gte", 0)),
                name="sale_discount_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="saleline",
            constraint=models.CheckConstraint(
                condition=models.Q(("gold_price_per_gram__gt", 0)),
                name="sale_line_gold_price_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="saleline",
            constraint=models.CheckConstraint(
                condition=models.Q(("making_charge_per_gram__gte", 0)),
                name="sale_line_making_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="saleline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="sale_line_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="saleline",
            constraint=models.UniqueConstraint(
                fields=("sale", "item"),
                name="sale_line_item_unique",
                violation_error_message="The same inventory item cannot appear more than once in a sale.",
            ),
        ),
    ]
